spring.application.name=stockflow

# Configurações de Conexão MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/stockflow_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=nexasystems
spring.datasource.password=senha_segura_senai
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Porta do Servidor (Usa a porta dinâmica do Render se disponível, ou 8081 por padrão localmente)
server.port=${PORT:8081}
